name: main_workflow

on:
  push:
    branches:
      - nodejs_linter_job

jobs:
  linter-execution:
    runs-on: ubuntu-latest

    steps:
      # Checkout del codi font
      - name: Checkout code
        uses: actions/checkout@v2

      # Executar el linter
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

